### ISSUE TITLE
Web Demo file load error

### ISSUE THREAD

**Issue by tarepan** [kbumsik/opus-media-recorder#11]
# Summary
Web demo (https://kbumsik.io/opus-media-recorder/) show error and cannot record audio with all codecs.

# Detail Situation
I try web demo of this great library (Windows10, Chrome72).  
Demo page was loaded and page contents looks normal.  
I can push "create" button.  
Then I try push "start" button, nothing happen.  

# Error Log
I checked Chrome console and found errors.  
```
Failed to load resource: the server responded with a status of 404 ()
```
```
GET https://kbumsik.io/opus-media-recorder/encoderWorker.umd.js 404
```

**Comment by kbumsik** [comment]
Opps, I took a mistake when I modularize encoderWorker.umd.js a week ago: 1a97a60018d78d7e29b3a2291bfb3f9678ffee59
Thank you very much for reporting this!
