### ISSUE TITLE
HTML <script> tag load failed

### ISSUE THREAD

**Issue by tarepan** [kbumsik/opus-media-recorder#12]
# Summary
When I load this library through HTML <script> tag, library loading failed.  

# Situation
I try to use this great library in browser through HTML <script> tag (Windows10, Chrome72).  
Chrome console said that library is missing.

# Error log
```
Failed to load resource: the server responded with a status of 404 () encoderWorker.umd.js:1
```

# Related problem
This error seems to be related to #11 
Some file is missing...?

**Comment by kbumsik** [comment]
This is pretty much the same issue as #11, you can discuss about it there.
Thank you for reporting this issue :)
