### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from WebMOpusEncoder.wasm

### ISSUE THREAD

**Issue by banstola** [kbumsik/opus-media-recorder#21]
Hi,
I am trying to use OpusMediaRecorder as default recorder by

` window.MediaRecorder = OpusMediaRecorder;`

But I get 
Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': Failed to parse URL from WebMOpusEncoder.wasm

**Comment by kbumsik** [comment]
Hi,
opus-media-recorder doesn't simply work by just assigning. It looks like you didn't set `workerOptions` correctly. Could you post your full code, to see how you import the module?

See [the documentation](https://github.com/kbumsik/opus-media-recorder#working-with-a-bundler) to configure `workerOptions` correctly.

**Comment by banstola** [comment]
Hi ,
Thank you for your prompt response.
I am just trying to figure out how to use it on existing project where mediarecorder does not work correctly at Firefox
```
<!-- load OpusMediaRecorder.umd.js. OpusMediaRecorder will be loaded. -->
<script src="https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/OpusMediaRecorder.umd.js"></script>
<!-- load encoderWorker.umd.js. This should be after OpusMediaRecorder. -->
<!-- This script tag will create OpusMediaRecorder.encoderWorker. -->
<script src="https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/encoderWorker.umd.js"></script>

<script>

    $(document).ready(function() {

        // If you already load encoderWorker.js using <script> tag,
        // you don't need to define encoderWorkerFactory.
        const workerOptions = {
            OggOpusEncoderWasmPath: 'https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/OggOpusEncoder.wasm',
            WebMOpusEncoderWasmPath: 'https://cdn.jsdelivr.net/npm/opus-media-recorder@latest/WebMOpusEncoder.wasm'
        };

        // Replace MediaRecorder
        window.MediaRecorder = OpusMediaRecorder;

```

**Comment by banstola** [comment]
Is it sufficient to include those files using those cdn links?

**Comment by kbumsik** [comment]
@banstola Hi, I make a minimal example using <script> tag for you.

https://jsfiddle.net/kbumsik/v3wpnxao/

This should work with any browser.

**Comment by banstola** [comment]
Thank you!
