### ISSUE TITLE
react not working

### ISSUE THREAD

**Issue by roxdavirox** [kbumsik/opus-media-recorder#33]
error FileName: http://localhost:3000/opus-media-recorder/encoderWorker.umd.js - LineNumber: 1 - Message: Uncaught SyntaxError: Unexpected token '<'

anybody has this problem?

**Comment by exPHAT** [comment]
Sounds like theres an issue hosting the worker files, can you ensure that they're being served at the correct path?

**Comment by roxdavirox** [comment]
I solve moving files to public react folder. but, i got another solution using mp3 XD

**Comment by rishikesh1419** [comment]
@roxdavirox  Which solution are you using instead?
